<?php return array (
  30 => '0 Overseas Resident',
  32 => '1 Australian PR',
  31 => '2 Australian Citizen',
  33 => '3 Conveyance',
  18 => 'Business Migration',
  25 => 'Carer Visa',
  20 => 'Child visa',
  12 => 'Citizenship',
  34 => 'Client Service',
  24 => 'Family migration',
  35 => 'Global Service',
  17 => 'Legal Research',
  26 => 'Medical Treatment',
  29 => 'NZ citizen family relation',
  3 => 'Parent Visa',
  10 => 'Partner visa',
  23 => 'Refugee Visa',
  14 => 'Resident Return Visa',
  1 => 'Skill Visa',
  5 => 'Student Visa',
  9 => 'visa complaince',
  6 => 'visit visa',
  15 => 'working holiday visa',
  13 => 'Working Visa',
);
